### ISSUE TITLE
Exceptions when starting unity (Favorites tab)

### ISSUE THREAD

**Issue by widugastir** [UnitySuperEditor/SuperEditor#1]
![image](https://user-images.githubusercontent.com/65368143/114296566-c1bb4b00-9ab4-11eb-95d8-51b43110e3dc.png)

Exceptions when starting unity with an open Favorites tab

**Comment by widugastir** [comment]
![image](https://user-images.githubusercontent.com/65368143/114297212-02689380-9ab8-11eb-9af8-d844dddaf176.png)

Also, I added the plugin to my project and the fonts were not loaded, so the code is not visible. Same warning.

**Comment by UnitySuperEditor** [comment]
You try to reimport the package, Can you show me your Project Window?

**Comment by widugastir** [comment]
> You try to reimport the package, Can you show me your Project Window?

![image](https://user-images.githubusercontent.com/65368143/114297339-bff38680-9ab8-11eb-81b6-e3db0d572529.png)

**Comment by UnitySuperEditor** [comment]
Delete the entire SuperEditor, restart Unity, and then re-import it to see if there are any problems

**Comment by widugastir** [comment]
> Delete the entire SuperEditor, restart Unity, and then re-import it to see if there are any problems

Tried it, same problem: delete SuperEditor folder -> restart Unity -> import plugin again -> same warning (AssetDatabase.FindAssets: Folder not found: 'uperEditor\EditorResources/Fonts')

**Comment by UnitySuperEditor** [comment]
I think there may be a problem with your project Settings, and you can copy all of your assets to the new project, if you copy ProjectSettings and this problem occurs again, then you can be sure that ProjectSettings is the problem

**Comment by widugastir** [comment]
> I think there may be a problem with your project Settings, and you can copy all of your assets to the new project, if you copy ProjectSettings and this problem occurs again, then you can be sure that ProjectSettings is the problem

It's work, ty!
