### ISSUE TITLE
how to turn off left click = toggle enable

### ISSUE THREAD

**Issue by laurentopia** [UnitySuperEditor/SuperEditor#12]
I find myself mistakenly disabling component too easily so i'd rather all click = display in inspector or in IDE, which option allows that?

**Comment by UnitySuperEditor** [comment]
Hey guys, you're on the right track. The next version will include a safe mode that does not change the enable/disable state of components or the active state of game objects.
Thank you for your advice!

**Comment by UnitySuperEditor** [comment]
Hey guys, in the v1.6.0, the features you want have been added, good luck!
