### ISSUE TITLE
It broke Unity Ctrl-D duplicate file object.

### ISSUE THREAD

**Issue by victorkin11** [UnitySuperEditor/SuperEditor#14]
Try using Unity 3D 2020.3.6f1

**Comment by UnitySuperEditor** [comment]
If you close the code window, does the problem still occur?  is it a shortcut conflict prompt?

**Comment by victorkin11** [comment]
When I try it stand alone, it work!!
it look like some other asset have conflict with it, since there is several assets I use as same time, sorry can't tell where the problem, but I do remove the supereditor to make than project ctrl-D work again, so I think it is supereditor problem, but maybe it is other asset bad behave with conflict with supeedit.
