### ISSUE TITLE
Super Editor Pro no longer available from the Unity Asset Store???

### ISSUE THREAD

**Issue by uboel** [UnitySuperEditor/SuperEditor#17]
Hello,

When trying to import your package in a new project, the Asset Store returns a message saying the Super Editor Pro is not available anymore????

<img width="812" alt="Capture d’écran 2021-06-03 à 22 37 15" src="https://user-images.githubusercontent.com/28643164/120708845-6017cb80-c4bc-11eb-82ec-e080e79d818a.png">

How can I get the Pro version from GitHub?

Ulric

**Comment by UnitySuperEditor** [comment]
As the product was reported by an Asset Store developer, the product is now in the disabled state. I have contacted the Unity Asset Store team and are trying to restore the product. Please don't worry, I will try to make it online again.

**Comment by uboel** [comment]
Ok...I see...
A hater? Or a jealous?

I hope this won't put you into too much problems...

Cheers

Ulric

Le ven. 4 juin 2021 à 04:11, UnitySuperEditor ***@***.***> a
écrit :

**Comment by uboel** [comment]
Hi again,

Since I left a positive comment on your plugin, I've been contacted by the developer of "Script Inspector 3" stating the following:

"
Hi Ulric,

Flipbookee here, the author of Script Inspector 3.

I saw your review for Super Editor Pro and that you noticed the asset is not available anymore. That's because the Asset Store has taken it down after I and probably the author of QHierarchy reported the asset that it contains stolen code from my asset and QHierarchy, almost 100% identical to the originals. He's a repeat offender, he did the same about a year and a half ago, and the Asset Store has also taken that asset down. I'm sorry that you've become one of his victims, but I hope you can request a refund from the Asset Store and they'll approve that quickly.

If you really liked the ability to code right inside Unity, you may consider purchasing the original asset, my Script Inspector 3. It's about the same price, $39 while Super Editor Pro was $40 before it got taken down. I see you say you bought it for 18 Euros, which is about half of that so if you get the refund you could buy the Script Inspector 3 when it gets a 50%, which will be very soon. However, my asset is not bundled with QHierarchy.

If none of that works for you, please let me know and I'll try to find another solution.

Cheers,
Flipbookee 
"

Do you really just take their code and integrated both plugins together? If it's the case, that was not a smart move...
I hope you'll find a solution soon...

Kind regards,

Ulric

**Comment by UnitySuperEditor** [comment]
No, if you buy the two plugins he mentioned, you can try to install them and compare them with the Super Editor, you will find that the experience is completely different.

**Comment by uboel** [comment]
Hey, I believe you (I just forgot the ;-) after "smart move")!

Let's hope the UAS guys will quickly allow your plugin on the store...

Cheers,

Ulric

**Comment by uboel** [comment]
Hello,

Did you get any news yet from the Unity Asset Store? Any idea when the plugin will be allowed back to the store?

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
The Unity Copyright Team said they have received my counter-notification for the assets and they are in process, Based on the speed Unity is working at, I estimate it will be a week before the results are available

**Comment by uboel** [comment]
Ok. Thanks for the update.
Courage.

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
Hey guys, it's alive today, you can download it at the asset store.
Good luck!

**Comment by uboel** [comment]
Congratulations!

**Comment by uboel** [comment]
You've been reported once again???? Still the same guys? How frustrating! :-(

**Comment by UnitySuperEditor** [comment]
I'm sorry, it will probably take another ten days or so for it to be restored, and the next version will be released together at that time. The next version will introduce some nice Xcode-like design

**Comment by uboel** [comment]
Hi

No news from the Unity guys yet?

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
No, there has been no official response from Unity, I have resubmitted the new version, if there is no official response, I will give the whole product for free and will keep updating

**Comment by uboel** [comment]
> No, there has been no official response from Unity, I have resubmitted the new version, if there is no official response, I will give the whole product for free and will keep updating
