### ISSUE TITLE
Highlights errors in code

### ISSUE THREAD

**Issue by widugastir** [UnitySuperEditor/SuperEditor#2]
Highlights errors where there are no errors:
![image](https://user-images.githubusercontent.com/65368143/114308871-f7305a80-9aed-11eb-83b3-733ea681ffe0.png)
![image](https://user-images.githubusercontent.com/65368143/114308962-41b1d700-9aee-11eb-9b94-76164db71036.png)

And I think "Save All" button can be very useful

**Comment by UnitySuperEditor** [comment]
Hey guys, thanks for your feedback, these issues have been fixed in version 1.0.2 and you can download them in the latest release
