### ISSUE TITLE
Version 1.6.1 not yet available on Unity Asset Store?

### ISSUE THREAD

**Issue by uboel** [UnitySuperEditor/SuperEditor#24]
Hello,

Any idea when the version 1.6.1 (Pro) will be available from the Unity Asset Store?

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
Hi, I'm really sorry for replying you so late. You can download the latest version of Super Editor Pro on Github, because it is completely free now. I will update it all the time because I love it rather than for making money.

**Comment by uboel** [comment]
Hi,

No worries about the late reply! Thanks for your dedication!
At least you won't waste time anymore fighting with the Unity guys every time someone think you stole his code...

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
If you try their products, you will see that they are poorly designed and stupid to use. I would never compare a second-rate product to Super Editor, because Super Editor is made for crazy, paranoid artists and developers who want to achieve their dreams.
