### ISSUE TITLE
Wrong exception

### ISSUE THREAD

**Issue by widugastir** [UnitySuperEditor/SuperEditor#3]
![image](https://user-images.githubusercontent.com/65368143/115002294-3c1d0e00-9ead-11eb-8338-59fc735b81ee.png)

**Comment by UnitySuperEditor** [comment]
Thanks for your feedback, this issue is being fixed
If you don't want this to appear right now, you can just pull out RaycastHit in its own right, like this
RaycastHit hit;
Physics.Raycast(ray,  hit,  Mathf.Infinity, colliderPlaneLayer)
