### ISSUE TITLE
External Editor workflow in 2.0.0?

### ISSUE THREAD

**Issue by JustusPan** [UnitySuperEditor/SuperEditor#34]
Is there any option allow us open the files directly using external editor?

**Comment by UnitySuperEditor** [comment]
Hi, I am busy with game development recently, so maybe there are few new features in Super Editor. In version 2.0.1, the function of Old mode has been changed. If you choose Old mode in mode toggle, the file will be opened in the external IDE. Old Mode takes the traditional Unity workflow mode of double-clicking the script to open the external IDE and only upgrades Unity Inspector's display. I will update the Super Editor regularly. Thank you for your constant support!

**Comment by JustusPan** [comment]
Works perfectly with 2.0.1.
1) upgrade to 2.0.1
2) switch to Quick Mode first
3) switch back to Old Mode

Now, every single click will only update the inspect preview, and every double-click will trigger the external editor.
Thanks for you excellect work.
