### ISSUE TITLE
Please move your asset so it is in the plugins folder

### ISSUE THREAD

**Issue by Shadowblitz16** [UnitySuperEditor/SuperEditor#4]
Can you move it to where Sirenix is?
![image](https://user-images.githubusercontent.com/2453707/116801755-713a7a80-aac1-11eb-9168-af696e1ae896.png)

**Comment by UnitySuperEditor** [comment]
Yes, this operation is allowed, you can move it to any folder

**Comment by Shadowblitz16** [comment]
does it have to be imported into that folder?
I moved it in their after importing it and it gave errors.

Looks like it doesn't now though hmm

**Comment by UnitySuperEditor** [comment]
I tried to download it from the Asset Store and then moved it to the Plugins folder, which I used normally
<img width="827" alt="2C742866-29B7-46ED-BE6F-7BB51CF0313D" src="https://user-images.githubusercontent.com/72157947/116803389-befac580-ab49-11eb-8215-d8d35f39c97e.png">
Could you try restarting the editor?

**Comment by Shadowblitz16** [comment]
looks like that worked.
can this be the default option?

**Comment by UnitySuperEditor** [comment]
If you want to move to any file, remember to Reimport SuperEditor. This is a problem with the Unity engine's internal setup for compiling DLL files

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor  so I.. 
1. import the super editor folder in the package manager 
2. move it to plugins
3. repeat 1?

**Comment by UnitySuperEditor** [comment]
<img width="606" alt="屏幕快照 2021-05-04 上午8 30 37" src="https://user-images.githubusercontent.com/72157947/116948921-52033f00-acb3-11eb-91fb-2d38c44d3e42.png">
No, right click menu

**Comment by Shadowblitz16** [comment]
ok thankyou.
is there a reason why you don't want to import it there by default?

**Comment by UnitySuperEditor** [comment]
Keep it simple, too many plugin developers put their plugins in the plugins directory and let users confuse their projects, but if you want to move SuperEditor to another directory, that's fine.

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor ya I understand it would be nice if unity allowed importing plugins and assets to the packages folder
