### ISSUE TITLE
Type Lags in Linux

### ISSUE THREAD

**Issue by Mohammad9760** [UnitySuperEditor/SuperEditor#43]
this didn't happen in Windows but I recently switched to Linux.
when I type something the typing stops whenever the auto complete window pops up. for example if I type "while" it only types "whi" and then I have to type the rest of it again letter by letter.
also I'm using it in Unity 2022 which when importing prompted me to update the compiled library or something.
is this a known issue in linux or Unity 2022??

**Comment by Mohammad9760** [comment]
so there's no help?
if you need any more info or anything just ask :(

**Comment by Mohammad9760** [comment]
I tried 1.4 and it would still get stuck on some keywords but it was slightly better

**Comment by Shadowblitz16** [comment]
I reported this issue as well.
I get it from script inspector 3 though too.
