### ISSUE TITLE
Cannot find fonts

### ISSUE THREAD

**Issue by Shadowblitz16** [UnitySuperEditor/SuperEditor#5]
![image](https://user-images.githubusercontent.com/2453707/116801925-5d901380-aac3-11eb-8413-f63088e2998d.png)
![image](https://user-images.githubusercontent.com/2453707/116801931-71d41080-aac3-11eb-8907-0a10de206b74.png)
![image](https://user-images.githubusercontent.com/2453707/116801966-c11a4100-aac3-11eb-8a3d-a37648e80191.png)

**Comment by UnitySuperEditor** [comment]
Hi，could you try to recreate a new project and then re-import it to see if there are any problems？

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor this is a new project.
![image](https://user-images.githubusercontent.com/2453707/116802585-b01ffe80-aac8-11eb-975f-9f09c37d6819.png)

The two plugins I just got done importing and the script is empty.
The scene the the default one that comes with unity.

I did move the SuperEditor folder to the plugins folder and got errors so I moved it back. I guess I can try deleting it and reimporting

**Comment by UnitySuperEditor** [comment]
It was handled separately on Mac OS and Windows, are you a Linux Unity Editor? I haven't tested it here

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor new project doesn't work either
the steps I did was..
- create new project
- import SuperEditor from package manager
- create new script
- double click on script to open it
![image](https://user-images.githubusercontent.com/2453707/116826350-6aa31600-ab48-11eb-9ba8-3c8d7a16a015.png)

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor was this fixed?
you didn't say why you closed the issue
