### ISSUE TITLE
Settings->Settings->Hierarchy crashes or freezes editor

### ISSUE THREAD

**Issue by Shadowblitz16** [UnitySuperEditor/SuperEditor#6]
![image](https://user-images.githubusercontent.com/2453707/116802008-1b1b0680-aac4-11eb-8d2c-2fed3224c08a.png)
![image](https://user-images.githubusercontent.com/2453707/116802010-22421480-aac4-11eb-9890-f76464721d13.png)

it froze unity first and then after reboot I tried again and it crashed it

**Comment by UnitySuperEditor** [comment]
Thank you for your feedback. This Hierarchy customization function is in the Pro version, which will pop up a Modal window, you can close it, and then you can continue to do your work. I will cancel this setting in the next version, because it does not bring good user experience

**Comment by Shadowblitz16** [comment]
as long as it doesn't crash or freeze the program its fine

**Comment by UnitySuperEditor** [comment]
Hey guys, This issue has been fixed in 1.2.1, The logic has been rewritten.
