### ISSUE TITLE
ArgumentException: Getting control 1's position in a group with only 1 controls when doing repaint

### ISSUE THREAD

**Issue by Shadowblitz16** [UnitySuperEditor/SuperEditor#7]
I get this when I try to type into the editor with no font. 
Not sure if it happens with font, that problem hasn't been fixed yet.
```
ArgumentException: Getting control 1's position in a group with only 1 controls when doing repaint
Aborting
UnityEngine.GUILayoutGroup.GetNext () (at /home/bokken/buildslave/unity/build/Modules/IMGUI/LayoutGroup.cs:129)
UnityEngine.GUILayoutUtility.BeginLayoutArea (UnityEngine.GUIStyle style, System.Type layoutType) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:361)
UnityEngine.GUILayoutUtility.DoBeginLayoutArea (UnityEngine.GUIStyle style, System.Type layoutType) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:378)
UnityEditor.EditorGUILayoutUtilityInternal.BeginLayoutArea (UnityEngine.GUIStyle style, System.Type LayoutType) (at /home/bokken/buildslave/unity/build/Editor/Mono/GUI/EditorGUIInternal.cs:97)
UnityEditor.GUIView.BeginOffsetArea (UnityEngine.Rect screenRect, UnityEngine.GUIContent content, UnityEngine.GUIStyle style) (at /home/bokken/buildslave/unity/build/Editor/Mono/GUIView.cs:239)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at /home/bokken/buildslave/unity/build/Editor/Mono/HostView.cs:394)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at /home/bokken/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:382)
UnityEditor.DockArea.OldOnGUI () (at /home/bokken/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:372)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:353)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:663)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:530)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRenderer/UIRenderers.cs:114)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRChainBuilder.cs:510)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRRepaintUpdater.cs:62)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/VisualTreeUpdater.cs:83)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:829)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:865)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:441)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:209)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:74)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at /home/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:28)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```
![image](https://user-images.githubusercontent.com/2453707/116822479-ce6f1400-ab33-11eb-9657-cf35d774eb0c.png)

**Comment by UnitySuperEditor** [comment]
This issue will be fixed in the next release, it is a path issue, the package I released on Mac was not fully tested, I will release the latest version later.

**Comment by Shadowblitz16** [comment]
I'm on linux tho :p

**Comment by UnitySuperEditor** [comment]
Hey guys, This issue has been fixed and has been found to be a mix-up between '/' and '\'. You can download version 1.2.1 here  releases or download it from the Asset Store while the Unity Asset Store team is working. Thanks for your feedback and make it better!

**Comment by Shadowblitz16** [comment]
![image](https://user-images.githubusercontent.com/2453707/116929333-216bc880-ac13-11eb-84e5-35bdaa095f7f.png)

**Comment by UnitySuperEditor** [comment]
Does the default import have this error？

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor yes.
it doesn't happen at first when opening a script but if you type into the script editor with no font repeatedly it throws the error.

**Comment by UnitySuperEditor** [comment]
I have downloaded the Ubuntu version of Linux and tested it. Part of the logic does not deal with Linux platforms, only Mac OS and Windows. In the next version, I will try to fix all the problems in Linux. It will probably be released this week, please wait patiently

**Comment by UnitySuperEditor** [comment]
The new version 1.2.2 has been released, which fixes a number of bugs on Linux systems. You can download it and try it out. If you find any problems, please feel free to feedback, Thank you for your feedback!

**Comment by Shadowblitz16** [comment]
@UnitySuperEditor no still didn't work
![image](https://user-images.githubusercontent.com/2453707/117521219-75ebac80-af61-11eb-8d7c-043cb2e8b005.png)
![image](https://user-images.githubusercontent.com/2453707/117521228-89971300-af61-11eb-928b-38ffc3fd194b.png)
![image](https://user-images.githubusercontent.com/2453707/117521235-96b40200-af61-11eb-8d27-671726d690e1.png)

**Comment by UnitySuperEditor** [comment]
Is there a font in the Settings？
<img width="886" alt="屏幕快照 2021-05-08 上午5 24 03" src="https://user-images.githubusercontent.com/72157947/117521416-3d3ee800-afe0-11eb-896d-c82c8b46130e.png">

**Comment by UnitySuperEditor** [comment]
I think it may be that the API output of.NET is different for different operating platforms. I will find a more general way to solve this tricky problem

**Comment by UnitySuperEditor** [comment]
No problem, any bugs are welcome, and making it more robust is something everyone would be happy to do,Does the tool work now？

**Comment by UnitySuperEditor** [comment]
> Is there a font in the Settings？
> Then you pull the SuperEditor out of the plugins directory and put it directly in the Assets directory and let me see if it works
> <img alt="屏幕快照 2021-05-08 上午5 24 03" width="886" src="https://user-images.githubusercontent.com/72157947/117521416-3d3ee800-afe0-11eb-896d-c82c8b46130e.png">

**Comment by UnitySuperEditor** [comment]
[SuperEditor.dll.zip](https://github.com/UnitySuperEditor/SuperEditor/files/6445149/SuperEditor.dll.zip)
Try this DLL, I guess it should work, and if it does I'll use it in the next version

**Comment by Shadowblitz16** [comment]
I'm not sure how to use C# libraries directly.
Can you give some instructions?

**Comment by UnitySuperEditor** [comment]
Just replace the original supereditor.dll

**Comment by Shadowblitz16** [comment]
it worked!
![image](https://user-images.githubusercontent.com/2453707/117526229-95420400-af78-11eb-8093-e74d095f0ad9.png)
