### ISSUE TITLE
SuperEditor Pro not working anymore on both MacOS and Windows

### ISSUE THREAD

**Issue by uboel** [UnitySuperEditor/SuperEditor#9]
Hello,

I bought the Pro version on Monday the 3rd of May and it was working properly event after I updated to version 1.21. 
Starting yesterday (I don't remember if I used Unity on Tuesday), impossible to get my code displayed in a FileWindow and when I try to type in something, I get the following message error :

NullReferenceException: Object reference not set to an instance of an object
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.ECHNBDOIENAKNANPOMDPBIMCFMFIHOHPKCPG.GetCompletions (CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.IGBAGDLMMPCHFDHMHNBCIFPKOFPFGDOKBLKB completionTypes, CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.CDOGDHKAGHAGGMOGLODGGKGNIIPNHLLEEDLL+IGBOILJOGGCEJBOMKOICAEPGHJANFJPMDEPG parseTreeNode, System.Collections.Generic.HashSet`1[T] completionSymbols, System.String assetPath) (at <53e7a6b74e104cb29276babb65ebc45a>:0)
UnityEngine.Debug:LogException(Exception)
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.ECHNBDOIENAKNANPOMDPBIMCFMFIHOHPKCPG:GetCompletions(IGBAGDLMMPCHFDHMHNBCIFPKOFPFGDOKBLKB, IGBOILJOGGCEJBOMKOICAEPGHJANFJPMDEPG, HashSet`1, String)
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.LBBGPIDBLEGLKGGBIIFGOBJNOJGIILIIEFMM:Autocomplete(Boolean)
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.LBBGPIDBLEGLKGGBIIFGOBJNOJGIILIIEFMM:DoGUIWithAutocomplete(Boolean)
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.LBBGPIDBLEGLKGGBIIFGOBJNOJGIILIIEFMM:OnWindowGUI(EditorWindow, RectOffset)
CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK.CGHBNFMMNFMFJNOPDHLEBKJFABAGBPBNAALK:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

Followed a couple of minutes after by messages like:

Resource ID out of range in GetResource: 1048577 (max is 1048575)
Resource ID out of range in SetResource: 1048577 (max is 1048575)

Until I close the FileWindow or wait for Unity to crash...

I tested also on my MacBook Pro. I get the same kind of behaviour but I also receive a message complaining about the "EditorResources/Fonts" folder not found.

This is just an Code Editor problem it seems. The Hierarchy widgets, the Options panel are working as expected.

I tried to revert to the non-Pro 1.1.2 and 1.20 versions and ran into the same problem.
I tested using Unity 2019.6f1, Unity 2019.7f1and Unity 2021.1.5f1.

I suppose this is due to a change in another Unity packages. I remember updating TextMeshPro, Timeline, Visual Studio Code Editor and Visual Studio Editor packages so I decided to revert back each one of these to a couple of versions back...but still no luck making the FileWindow editor back to work...

I hope you'll find the source of the problem and you'll be able to provide a patch to this soon...I really love coding directly in the Unity Editor! ;-)

Cheers,

Ulric

**Comment by UnitySuperEditor** [comment]
hi guys,Version 1.2.1 fixes an issue where previous version updates would close all FileWindow, and you might need to Reimport SuperEditor,Updates after 1.2.1 will not affect any of your open code Windows as if nothing had happened, but previous releases will close all of your code Windows.
Can you delete the Super Editor and then re-import it from Package manager  to see if there are any other errors？
Thank you for your Support!

**Comment by uboel** [comment]
Hi,

I already tried removing the installed package from my project and reimporting it. 
I also tried importing the package and then restarting Unity before testing the editor. 
I even removed the unitypackage file the hub cache and redownloaded it. 
I started a new project and imported the freshly downloaded package... each time, I got the same result... :-(

Ulric

**Comment by UnitySuperEditor** [comment]
I just imported from the asset store to test it is OK, you first create a blank project, and then re-import to see if there is any problem

**Comment by UnitySuperEditor** [comment]
Could you please send me the screenshot of the Console and  the Project?

**Comment by UnitySuperEditor** [comment]
In the next version, I'm going to add an emergency handling mechanism, which is to search for fonts in a fixed path at the end, because currently I get the font path completely dynamically

**Comment by uboel** [comment]
Well...I tested the new version on my Windows machine (both update and complete reinstall of the plugin)...no luck. 
I completely uninstalled the 3 Unity versions I had, I uninstalled the Hub, I cleaned all the cached files and did some Registry  Unity related cleanup then restarted my computer. I reinstalled the Hub and the latest 2020 LTS version. I then started a new project, downloaded the latest plugin version from the Package Manager...no more luck.
When opening a fresh behaviour script, the pane stays empty.

On my Mac, the editor stays also empty.
<img width="1552" alt="Capture d’écran 2021-05-07 à 21 02 56" src="https://user-images.githubusercontent.com/28643164/117497125-50b66880-af78-11eb-8dc0-7fcb6f1865ef.png">


What's quite strange is that I also have the exact same problem with all the previous versions of the plugin.

**Comment by UnitySuperEditor** [comment]
If you create a new blank project, will the problem be the same after import？

**Comment by UnitySuperEditor** [comment]
Please try backing up the Project Settings and deleting it ,and reimport the SuperEditor,And then see if there are any problems

**Comment by uboel** [comment]
No improvement...sorry...

**Comment by UnitySuperEditor** [comment]
Try deleting the editor preferences file,It's separate from the Unity editor path, and see if there are any problems
<img width="855" alt="屏幕快照 2021-05-08 上午3 43 44" src="https://user-images.githubusercontent.com/72157947/117500879-d86b9980-afaf-11eb-8bd6-feec2ae5b050.png">

**Comment by uboel** [comment]
Nope...still the same empty windows

**Comment by UnitySuperEditor** [comment]
[SuperEditor.dll.zip](https://github.com/UnitySuperEditor/SuperEditor/files/6445194/SuperEditor.dll.zip)
Try this DLL and I guess it should work,If it works, I'll use this in the next release
Just replace the original supereditor.dll,This time I used all the Unity internal methods and deleted the Microsoft methods
<img width="275" alt="屏幕快照 2021-05-08 下午12 06 27" src="https://user-images.githubusercontent.com/72157947/117526375-47201580-aff7-11eb-97a5-5d378e58e81b.png">

**Comment by uboel** [comment]
YES ! A big YES !!! A huuuuuge YES !!! It seems to work properly !!!

<img width="1552" alt="Capture d’écran 2021-05-08 à 07 42 31" src="https://user-images.githubusercontent.com/28643164/117528184-30ff5e80-afd1-11eb-86a6-c246e5ef2c5d.png">

Many thanks for the dedication you put into this ticket!

Ulric
